### ISSUE TITLE
Syncthing losing attached folder after changing refresh interval

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#316] opened 2015-03-08 12:34 UTC
So, the 5 second time frame as a little too high for the Johnbot.  I changed it to 2 seconds at the 127.0.0.1:60008 && 10.13.37.42:60008 ips addresses.

After a minute or so, all of a sudden my files were not syncing anymore.  I checked the 127.0.0.1 address and noticed the key with my current app was not connected.  Strange, I thought, so I hit refresh and nothing happened.  I clicked edit on the key for the app in question and noticed the check mark next tot he folder for the app was off now.  I re-checked it and it was happy again.  

Could of been a glitch in the matrix, but I thought I would put this up here in case I see it again or others do.

**Comment by pirog** [comment] 2015-03-08 18:20
Can you provide some more detail here? 

Have you run into the issue since?

**Comment by labboy0276** [comment] 2015-03-08 19:21
What else shall you need for info?  I tried to reproduce base don what I did above to no avail.  It seemed like it only happened the one time.

**Comment by pirog** [comment] 2015-03-08 19:24
Thats good to know.

We will try to reproduce a few times and if we cant we will probably just
close this out for now.

Def continue to post any syncthing weirdness though. That is one of the key
areas we need to shore up for this whole thing to work.

Beyond that has it worked as expected?

On Sun, Mar 8, 2015 at 12:21 PM, John Ouellet <notifications@github.com>
wrote:

> What else shall you need for info? I tried to reproduce base don what I
> did above to no avail. It seemed like it only happened the one time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/316#issuecomment-77768853>
> .
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment] 2015-03-08 19:30
Other than that it worked flawlessly.  I worked on that one site no problemo.

It was mucho faster.  Setting the time to 2 seconds seems to be the bestest when working with grunt and such as well.

**Comment by pirog** [comment] 2015-03-08 19:33
awesome. @bcauldwell and i will think about moving the interval time down
to 2 seconds.

let us know if you run into any other issues so we can fix them asap.

On Sun, Mar 8, 2015 at 12:30 PM, John Ouellet <notifications@github.com>
wrote:

> Other than that it worked flawlessly. I worked on that one site no
> problemo.
>
> It was mucho faster. Setting the time to 2 seconds seems to be the bestest
> when working with grunt and such as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/316#issuecomment-77769304>
> .
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment] 2015-03-08 19:37
Indeed

I will be moving all my sites now to kb2 now whilst I do the kalacare, so long kb1 it has been fun

**Comment by pirog** [comment] 2015-03-08 19:42
Nice nice!

ill work to try to get xdebug in there this week

On Sun, Mar 8, 2015 at 12:37 PM, John Ouellet <notifications@github.com>
wrote:

> Indeed
>
> I will be moving all my sites now to kb2 now whilst I do the kalacare, so
> long kb1 it has been fun
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/316#issuecomment-77769688>
> .
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by bcauldwell** [comment] 2015-03-08 19:44
I was really hoping we could get away with 5s intervals, but looks like 2s interval wins!

**Closed** 2015-04-15 19:17 UTC
Labels: 1
